version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "15432:5432"

    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafaelmadakis@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge