server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelmadakis/ead-config-server-repo
          defaultLabel: main
          username: rafaelmadakis
          password:
ead:
  configServer:
    username: configserver
    password:
  serviceRegistry:
    username: serviceRegistry
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
